apiVersion: v1
kind: Service
metadata:
  name: app  # Nome do serviço
spec:
  selector:
    app: app  # Rótulo para selecionar os pods correspondentes
  ports:
    - protocol: TCP  # Protocolo utilizado (TCP neste caso)
      port: 80  # Porta externa do serviço
      targetPort: 5000  # Porta interna do pod de destino
  type: LoadBalancer  # Tipo de serviço (LoadBalancer neste caso)
