name: Criar EC2 e instalar Jenkins

on:
  push:
    branches:
      - main

jobs:
  create_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
      - name: Criar instância EC2
        id: create_ec2
        uses: aws-actions/aws-cli@v2
        with:
          args: aws ec2 run-instances --image-id ami-06ca3ca175f37dd66 --instance-type t2.micro --subnet-id subnet-0c48f0aa9f230519c --security-group-ids sg-0d7cf2e6d0ea2ad37

      - name: Esperar até que a instância esteja em execução
        id: wait_for_instance
        uses: aws-actions/aws-cli@v2
        with:
          args: ec2 wait instance-running --instance-ids ${{ steps.create_ec2.outputs.Instances }}

  install_jenkins:
    runs-on: ubuntu-latest
    needs: create_ec2
    steps:
      - name: Configurar ambiente AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Aguardar até que a instância esteja em execução
        id: wait_for_instance_2
        uses: aws-actions/wait-for@v1
        with:
          resources: ${{ needs.create_ec2.outputs.instance-id }}
          timeout: '10m'

      - name: Instalar Jenkins
        run: |
          ssh-keyscan -H ${{ needs.create_ec2.outputs.public-ip }} >> ~/.ssh/known_hosts
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem
          scp -i private_key.pem jenkins.sh ec2-user@${{ needs.create_ec2.outputs.public-ip }}:~/jenkins.sh
          ssh -i private_key.pem ec2-user@${{ needs.create_ec2.outputs.public-ip }} 'bash ~/jenkins.sh'
