name: Build and Deploy to EKS
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get commit SHA
        id: commit_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build Docker image
        run: |
          docker build -t w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }} .

      - name: Push image to Docker Hub
        run: |
          docker push w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Substitua pela região AWS correta

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name cluster-app --region us-east-1 # Substitua pelo nome do cluster EKS e pela região AWS correta

      - name: Deploy to EKS
        run: |
          kubectl apply -k ./k8s
