name: Build and Deploy to EKS  # Nome do fluxo de trabalho
on:
  push:  # Desencadeado por um push para o repositório
    branches:
      - main  # Apenas para a branch "main"

jobs:
  build-and-deploy:  # Nome do job
    runs-on: ubuntu-latest  # Executa em uma máquina com sistema operacional Ubuntu

    steps:  # Etapas do job
      - name: Checkout the code  # Passo para realizar o checkout do código
        uses: actions/checkout@v2  # Usa a ação de checkout do GitHub Actions

      - name: Login to Docker Hub  # Passo para fazer login no Docker Hub
        uses: docker/login-action@v1  # Usa a ação de login no Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Nome de usuário do Docker Hub
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Token de acesso ao Docker Hub

      - name: Get commit SHA  # Passo para obter o SHA do commit
        id: commit_sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build Docker image  # Passo para construir a imagem Docker
        run: |
          docker build -t w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }} .

      - name: Push image to Docker Hub  # Passo para enviar a imagem para o Docker Hub
        run: |
          docker push w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }}

      - name: Configure AWS credentials  # Passo para configurar as credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v1  # Usa a ação de configuração das credenciais da AWS
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # ID da chave de acesso da AWS
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Chave de acesso secreta da AWS
          aws-region: us-east-1  # Região AWS para a implantação (substitua pela região correta)

      - name: Setup Kustomize  # Passo para configurar o Kustomize
        uses: imranismail/setup-kustomize@v1  # Usa a ação de configuração do Kustomize
        with:
          kustomize-version: "3.6.1"  # Versão do Kustomize a ser usada

      - name: update k8s  # Passo para atualizar o arquivo de configuração do Kubernetes
        run: |
          cd k8s
          kustomize edit set image app=w3ll1n9t0n/app:${{ steps.commit_sha.outputs.sha_short }}
          cat kustomization.yaml

      - name: commit  # Passo para fazer o commit das alterações
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "change image tag"

      - name: Push para o GitHub  # Passo para fazer o push das alterações para o GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token de acesso ao GitHub
